const { logger } = require('../core/logger');

class SelfHealingService {
  constructor() {
    this.autoGeneratedRulesCount = 0;
  }

  analyzeAndHeal(req, threatScore, reasons, engine) {
    if (threatScore < 90) return; // Only trigger for highly confident critical attacks

    // Check if the attack was payload-based (XSS or SQLi)
    const isPayloadAttack = reasons.some(r => r.includes('SQL') || r.includes('XSS') || r.includes('NoSQL'));
    if (!isPayloadAttack) return;

    logger.info(`[Self-Healing] Critical attack payload detected (Score: ${threatScore}). Analyzing threat to compile adaptive rule...`);

    // Inspect request body/query/headers to extract the exact offending substring
    let offendingPayload = null;
    
    // Helper to find suspicious patterns in strings
    const containsSuspicious = (val) => {
      if (typeof val !== 'string') return false;
      return /<script|select\b|union\b|document\.cookie|xp_cmdshell|--|\/\*/i.test(val);
    };

    if (req.query) {
      for (const key in req.query) {
        if (containsSuspicious(req.query[key])) {
          offendingPayload = req.query[key];
          break;
        }
      }
    }

    if (!offendingPayload && req.body && typeof req.body === 'object') {
      for (const key in req.body) {
        if (containsSuspicious(req.body[key])) {
          offendingPayload = req.body[key];
          break;
        }
      }
    }

    if (offendingPayload && offendingPayload.length < 150) {
      // Escape special characters to create a safe regex rule
      const escaped = offendingPayload.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
      
      // Check if we already have this rule to prevent duplicate rules
      const ruleExists = engine.activeRules.some(r => typeof r === 'string' && r.includes(escaped));
      if (!ruleExists) {
        // Compile a custom DSL rule to block this payload instantly in O(1) time
        const newDslRule = `if (payload.includes("${offendingPayload}")) block()`;
        engine.activeRules.push(newDslRule);
        this.autoGeneratedRulesCount++;
        
        logger.info(`[Self-Healing] Adaptive WAF protection rule successfully generated and hot-patched: "${newDslRule}"`);
      }
    }
  }
}

module.exports = new SelfHealingService();
